# Site settings
title: 757btc.org
email: 757btc.org@proton.me
description: >-
  Collaborating and educating on Bitcoin, Nostr and Freedom Tech in Hampton Roads Virginia. We announce our meetings at the beginning of each month and meet on the 2nd Saturday of each month.
baseurl: ""
url: "https://www.757btc.org"
github_username: 757btc

# Theme settings
excerpt: true
post_navigation: true

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "posts/page:num"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Include .well-known for Nostr verification
include: [".well-known"]

# Exclude reference material and dev files
exclude:
  - reference
  - Gemfile
  - Gemfile.lock
  - README.md
